trigger: none

variables:
  registryName: 'acrdomedev001'
  imageRepository: 'dome-wallet-frontend'
  azureSubscription: 'Entorno Cloud DOME DEV'
  dockerRegistryServiceConnection: 'ACR DEV'
  dockerfilePath: '$(System.DefaultWorkingDirectory)/Dockerfile'
      
pool:
  vmImage: ubuntu-latest

stages:
  - stage: Upload_dockerfile_to_ACR
    pool: 
      vmImage: 'ubuntu-latest'
    jobs:
      - job:  
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'SonarCloud'
              organization: 'in2dome'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'in2Dome_in2-dome-wallet' 
              projectKey: 'in2Dome_in2-dome-wallet'
              projectName: 'in2-dome-wallet'
              cliSources: '.' #$(Build.SourcesDirectory)
                
          - task: SonarCloudAnalyze@1

          - task: SonarCloudPublish@1
            inputs:
                pollingTimeoutSec: '300'
          - task: Docker@2
            displayName: Build and push an image to container registry
            inputs:
              command: buildAndPush
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: latest
